apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appointment/deployment.yaml
  - appointment/service.yaml
  - patient/deployment.yaml
  - patient/service.yaml
  - order/deployment.yaml
  - order/service.yaml
  - ingress.yaml
