name: Build & Push Images

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: steel-magpie-486007-d6
  REGION: asia-south1
  REPO: hackathon
  REGISTRY: asia-south1-docker.pkg.dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for Workload Identity, to request an OIDC token from Github

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Auth to GCP
      # -------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          service_account: github-ci@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      # -------------------------
      # Appointment Service
      # -------------------------
      - name: Build & push appointment-service
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/appointment-service:latest \
            application-service

          docker push \
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/appointment-service:latest

      # -------------------------
      # Patient Service
      # -------------------------
      - name: Build & push patient-service
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/patient-service:latest \
            patient-service

          docker push \
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/patient-service:latest

      # -------------------------
      # Order Service (Java)
      # -------------------------
      - name: Build & push order-service
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/order-service:latest \
            order-service

          docker push \
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/order-service:latest
